name: gchat
description: A chat app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # GetX
  get: ^4.6.5

  # InfoCore
  device_info_plus: ^4.1.2
  package_info_plus: ^1.4.3+1

  # UI
  flutter_svg: ^1.1.5

  # DBCore
  hive: ^2.2.3
  path_provider: ^2.0.11

  # GraphCore
  graphql: ^5.1.1

  # StorageCore
  shared_preferences: ^2.0.15

  # ConnectionCore
  connectivity_plus: ^2.3.7
  flutter_localizations:
    sdk: flutter
  pinput: ^2.2.12
  custom_timer: ^0.1.2
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.2
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/avatars/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
